#pragma once

#ifndef __ENUM__H__

enum BULLET_DIRECTION 
{ 
	BULLET_LEFT, BULLET_RIGHT, BULLET_UP, BULLET_DOWN 
};

enum OBJECT_TYPE 
{ 
	OBJECT_BACKGROUND, OBJECT_PLAYER, OBJECT_MONSTER, OBJLECT_BULLET,OBJECT_FLOOR,OBJECT_ITEM, OBJECT_OBSTACLE,OBJECT_JELLY,
	OBJECT_SHIELD, OBJECT_MOUSE, OBJECT_END 
};
enum OBSTACLE_TYPE
{
	//정적 장애물
	OBSTACLE_GIMLET,OBSTACLE_GIMLET2,OBSTACLE_FORK,OBSTACLE_FORK1,OBSTACLE_FORK2,OBSTACLE_FORK3,OBSTACLE_FORK4,OBSTACLE_LONGFORK,
	//스테이지2 장애물
	OBSTACLE_PORTION,OBSTACLE_PORTION2,OBSTACLE_SKULL,OBSTACLE_ONION,OBSTACLE_FROG,OBSTACLE_TRAP,OBSTACLE_TRAP2,
	//가시 애니메이션
	OBSTACLE_GIMLETS,OBSTACLE_GIMLETS2,
	OBSTACLE_MUD,OBSTACLE_END
};
enum OBSTACLE_MOVETYPE
{
	STOP,FALLING,UPTODOWN,ANIMATION,MOVETYPE_END
};
enum ITEM_TYPE
{
	ITEM_HEALTH, ITEM_MAGNET,ITEM_END
};

enum JELLY_TYPE
{
	YELLOW_BEAR, PINK_BEAR, BLUE_BEAN,JELLY_END
};

enum FLOOR_TYPE
{
	STAGE1_BOTTOM,STAGE1_HANG,STAGE2_BOTTOM,STAGE2_HANG
};

enum Scene
{
	STAGE1, STAGE2
};
#define __ENUM__H__
#endif
