#pragma once

#ifndef __ENUM__H__

enum BULLET_DIRECTION 
{ 
	BULLET_LEFT, BULLET_RIGHT, BULLET_UP, BULLET_DOWN 
};

enum OBJECT_TYPE 
{ 
	OBJECT_BACKGROUND, OBJECT_PLAYER, OBJECT_MONSTER, OBJLECT_BULLET,OBJECT_FLOOR,OBJECT_ITEM, 
	OBJECT_SHIELD, OBJECT_MOUSE, OBJECT_END 
};
enum ITEM_TYPE
{
	ITEM_JELLY, ITEM_HEALTH, ITEM_MAGNET,ITEM_END
};

enum JELLY_TYPE
{
	YELLOW_BEAR, PINK_BEAR, BLUE_BEAN,JELLY_END
};
#define __ENUM__H__
#endif
