#pragma once

#ifndef __ENUM__H__

enum BULLET_DIRECTION 
{ 
	BULLET_LEFT, BULLET_RIGHT, BULLET_UP, BULLET_DOWN 
};

enum OBJECT_TYPE 
{ 
	OBJECT_BACKGROUND, OBJECT_PLAYER, OBJECT_MONSTER, OBJLECT_BULLET, 
	OBJECT_SHIELD, OBJECT_MOUSE, OBJECT_END 
};

#define __ENUM__H__
#endif
